<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <ProjectReference Include="..\MonitorInfo.Windows\MonitorInfo.Windows.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <ProjectReference Include="..\MonitorInfo.macOS\MonitorInfo.macOS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MonitorInfo\MonitorInfo.csproj" />
  </ItemGroup>

</Project>
