<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlockSerial\BlockSerial.csproj" />
    <ProjectReference Include="..\WMA\WMAData\WMAData.csproj" />
  </ItemGroup>

</Project>
